# Generated by Django 5.1.5 on 2025-12-13 17:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
        ("projects", "0004_task_time_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="idea_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="boards.boardcard",
            ),
        ),
        migrations.CreateModel(
            name="TaskLink",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("url", models.URLField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="projects.task",
                    ),
                ),
            ],
        ),
    ]
