# Generated by Django 5.1.5 on 2025-12-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_task_idea_and_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('WORKSHOP', 'Workshop'), ('RETREAT', 'Retreat'), ('CONSULTATION', 'Consultation'), ('IT_SERVICE', 'IT Service'), ('MARKETING', 'Marketing'), ('DEVELOPMENT', 'Development'), ('DESIGN', 'Design'), ('RESEARCH', 'Research'), ('SALES', 'Sales'), ('FINANCE', 'Finance'), ('LEGAL', 'Legal'), ('HR', 'HR'), ('OPERATIONS', 'Operations'), ('EVENT', 'Event'), ('CONTENT', 'Content'), ('TRAINING', 'Training')], default='WORKSHOP', max_length=30),
        ),
    ]
