# Generated by Django 5.1.5 on 2025-12-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_project_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="subtitle",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
