# Generated by Django 5.1.5 on 2025-12-15 11:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_task_subtitle'),
        ('tenants', '0002_organizationinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('trigger_type', models.CharField(choices=[('task_created', 'Task Created'), ('status_changed', 'Status Changed'), ('task_updated', 'Task Updated'), ('due_date_approaching', 'Due Date Approaching'), ('due_date_reached', 'Due Date Reached'), ('due_date_overdue', 'Due Date Overdue'), ('label_added', 'Label Added'), ('label_removed', 'Label Removed'), ('assigned_to_user', 'Assigned to User'), ('priority_changed', 'Priority Changed'), ('task_completed', 'Task Completed')], max_length=32)),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_task_automation_rules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_automation_rules', to='tenants.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAutomationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to='projects.task')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='projects.taskautomationrule')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAutomationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('change_status', 'Change Status'), ('set_priority', 'Set Priority'), ('assign_user', 'Assign User'), ('unassign_user', 'Unassign User'), ('add_label', 'Add Label'), ('remove_label', 'Remove Label'), ('set_due_date', 'Set Due Date'), ('clear_due_date', 'Clear Due Date'), ('move_to_project', 'Move to Project'), ('send_notification', 'Send Notification'), ('post_comment', 'Post Comment'), ('add_to_calendar', 'Add to Calendar')], max_length=32)),
                ('action_config', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='projects.taskautomationrule')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TaskButton',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='play', max_length=50)),
                ('color', models.CharField(default='indigo', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_task_buttons', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_buttons', to='tenants.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_buttons', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskButtonAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('change_status', 'Change Status'), ('set_priority', 'Set Priority'), ('assign_user', 'Assign User'), ('unassign_user', 'Unassign User'), ('add_label', 'Add Label'), ('remove_label', 'Remove Label'), ('set_due_date', 'Set Due Date'), ('clear_due_date', 'Clear Due Date'), ('move_to_project', 'Move to Project'), ('send_notification', 'Send Notification'), ('post_comment', 'Post Comment'), ('add_to_calendar', 'Add to Calendar')], max_length=32)),
                ('action_config', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='projects.taskbutton')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TaskLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='gray', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_labels', to='tenants.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TaskLabelAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.tasklabel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_assignments', to='projects.task')),
            ],
            options={
                'unique_together': {('task', 'label')},
            },
        ),
    ]
