# Generated by Django 5.1.5 on 2025-12-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_task_archive_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskautomationaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("change_status", "Change Status"),
                    ("set_priority", "Set Priority"),
                    ("assign_user", "Assign User"),
                    ("unassign_user", "Unassign User"),
                    ("add_label", "Add Label"),
                    ("remove_label", "Remove Label"),
                    ("set_due_date", "Set Due Date"),
                    ("clear_due_date", "Clear Due Date"),
                    ("move_to_project", "Move to Project"),
                    ("send_notification", "Send Notification"),
                    ("post_comment", "Post Comment"),
                    ("add_to_calendar", "Add to Calendar"),
                    ("archive_task", "Archive Task"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="taskbuttonaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("change_status", "Change Status"),
                    ("set_priority", "Set Priority"),
                    ("assign_user", "Assign User"),
                    ("unassign_user", "Unassign User"),
                    ("add_label", "Add Label"),
                    ("remove_label", "Remove Label"),
                    ("set_due_date", "Set Due Date"),
                    ("clear_due_date", "Clear Due Date"),
                    ("move_to_project", "Move to Project"),
                    ("send_notification", "Send Notification"),
                    ("post_comment", "Post Comment"),
                    ("add_to_calendar", "Add to Calendar"),
                    ("archive_task", "Archive Task"),
                ],
                max_length=32,
            ),
        ),
    ]
