# Generated by Django 5.1.5 on 2025-12-20 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_add_archive_task_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskbutton",
            name="hide_when_has_label",
            field=models.ForeignKey(
                blank=True,
                help_text="Button hides when task has this label",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hidden_by_buttons",
                to="projects.tasklabel",
            ),
        ),
        migrations.AddField(
            model_name="taskbutton",
            name="show_on_priority",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of task priorities where this button should appear (empty = all)",
            ),
        ),
        migrations.AddField(
            model_name="taskbutton",
            name="show_on_status",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of task statuses where this button should appear (empty = all)",
            ),
        ),
        migrations.AddField(
            model_name="taskbutton",
            name="show_when_has_label",
            field=models.ForeignKey(
                blank=True,
                help_text="Button only shows when task has this label",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="required_by_buttons",
                to="projects.tasklabel",
            ),
        ),
    ]
