# Generated by Django 5.1.5 on 2026-01-07 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_add_project_archive_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskautomationrule',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskautomationrule',
            name='recurrence_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskautomationrule',
            name='recurrence_frequency',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='taskautomationrule',
            name='recurrence_interval',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='taskautomationrule',
            name='recurrence_max_occurrences',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskautomationrule',
            name='recurrence_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_children', to='projects.taskautomationrule'),
        ),
    ]
