# Generated by Django 5.1.5 on 2026-01-07 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_task_recurring_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_frequency', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=20, null=True)),
                ('recurrence_interval', models.PositiveIntegerField(default=1)),
                ('recurrence_end_date', models.DateTimeField(blank=True, null=True)),
                ('recurrence_max_occurrences', models.PositiveIntegerField(blank=True, null=True)),
                ('recurrence_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_children', to='projects.task')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurring', to='projects.task')),
            ],
        ),
    ]
