# Generated by Django 5.1.5 on 2026-01-07 19:13

from django.db import migrations


def migrate_recurring_data(apps, schema_editor):
    Task = apps.get_model('projects', 'Task')
    RecurringTask = apps.get_model('projects', 'RecurringTask')

    for task in Task.objects.filter(is_recurring=True):
        RecurringTask.objects.create(
            task=task,
            is_recurring=task.is_recurring,
            recurrence_frequency=task.recurrence_frequency,
            recurrence_interval=task.recurrence_interval,
            recurrence_end_date=task.recurrence_end_date,
            recurrence_max_occurrences=task.recurrence_max_occurrences,
            recurrence_parent=task.recurrence_parent,
        )


def reverse_migrate_recurring_data(apps, schema_editor):
    # Reverse migration if needed
    RecurringTask = apps.get_model('projects', 'RecurringTask')
    RecurringTask.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_recurringtask'),
    ]

    operations = [
        migrations.RunPython(
            migrate_recurring_data,
            reverse_code=reverse_migrate_recurring_data,
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='task',
            name='recurrence_end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='recurrence_frequency',
        ),
        migrations.RemoveField(
            model_name='task',
            name='recurrence_interval',
        ),
        migrations.RemoveField(
            model_name='task',
            name='recurrence_max_occurrences',
        ),
        migrations.RemoveField(
            model_name='task',
            name='recurrence_parent',
        ),
    ]
