# Generated by Django 5.1.5 on 2026-01-07 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_migrate_recurring_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurrence_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_children', to='projects.task'),
        ),
        migrations.AlterField(
            model_name='recurringtask',
            name='recurrence_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_task_children', to='projects.task'),
        ),
    ]
