# Generated by Django 5.1.5 on 2025-12-15 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_boardcard_aicontent_pack_settings_applied_preview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardCardAIContentPackSettings',
        ),
    ]
