# Generated by Django 5.1.5 on 2025-12-15 07:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_remove_ai_content_pack_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcard',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_board_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardcard',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('trigger_type', models.CharField(choices=[('card_created', 'Card Created'), ('card_moved', 'Card Moved'), ('card_updated', 'Card Updated'), ('due_date_approaching', 'Due Date Approaching'), ('due_date_reached', 'Due Date Reached'), ('due_date_overdue', 'Due Date Overdue'), ('label_added', 'Label Added'), ('label_removed', 'Label Removed'), ('checklist_completed', 'Checklist Completed')], max_length=32)),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='boards.board')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_automation_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to='boards.boardcard')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='boards.automationrule')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('move_card', 'Move Card'), ('move_to_top', 'Move to Top of List'), ('move_to_bottom', 'Move to Bottom of List'), ('assign_user', 'Assign User'), ('unassign_user', 'Unassign User'), ('add_label', 'Add Label'), ('remove_label', 'Remove Label'), ('set_due_date', 'Set Due Date'), ('clear_due_date', 'Clear Due Date'), ('add_checklist', 'Add Checklist'), ('send_notification', 'Send Notification'), ('post_comment', 'Post Comment')], max_length=32)),
                ('action_config', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='boards.automationrule')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='BoardCardLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='gray', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='boards.board')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('board', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CardButton',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='play', max_length=50)),
                ('color', models.CharField(default='indigo', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_buttons', to='boards.board')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_card_buttons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CardButtonAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('move_card', 'Move Card'), ('move_to_top', 'Move to Top of List'), ('move_to_bottom', 'Move to Bottom of List'), ('assign_user', 'Assign User'), ('unassign_user', 'Unassign User'), ('add_label', 'Add Label'), ('remove_label', 'Remove Label'), ('set_due_date', 'Set Due Date'), ('clear_due_date', 'Clear Due Date'), ('add_checklist', 'Add Checklist'), ('send_notification', 'Send Notification'), ('post_comment', 'Post Comment')], max_length=32)),
                ('action_config', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='boards.cardbutton')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='BoardCardLabelAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_assignments', to='boards.boardcard')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='boards.boardcardlabel')),
            ],
            options={
                'unique_together': {('card', 'label')},
            },
        ),
    ]
