# Generated by Django 5.1.5 on 2025-12-20 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0006_boardcard_assigned_to_boardcard_due_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardbutton",
            name="hide_when_has_label",
            field=models.ForeignKey(
                blank=True,
                help_text="Button hides when card has this label",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hidden_by_buttons",
                to="boards.boardcardlabel",
            ),
        ),
        migrations.AddField(
            model_name="cardbutton",
            name="show_when_has_label",
            field=models.ForeignKey(
                blank=True,
                help_text="Button only shows when card has this label",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="required_by_buttons",
                to="boards.boardcardlabel",
            ),
        ),
    ]
