# Generated by Django 5.1.5 on 2026-01-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='recipient_zip_city',
        ),
        migrations.AddField(
            model_name='invoice',
            name='recipient_zip',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='recipient_city',
            field=models.CharField(default='', max_length=255),
        ),
    ]
