# Generated by Django 5.1.5 on 2026-01-20 17:15
 
from django.db import migrations, models
 
 
class Migration(migrations.Migration):
 
    dependencies = [
        ("invoices", "0002_auto_20260120_1432"),
    ]
 
    operations = [
        migrations.AddField(
            model_name="invoice",
            name="pdf_template",
            field=models.CharField(
                choices=[
                    ("classic", "Classic"),
                    ("modern", "Modern"),
                    ("elegant", "Elegant"),
                    ("minimal", "Minimal"),
                ],
                default="classic",
                max_length=32,
            ),
        ),
    ]
