# Generated by Django 5.1.5 on 2026-01-21 09:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_invoice_company(apps, schema_editor):
    Company = apps.get_model("invoices", "Company")
    Invoice = apps.get_model("invoices", "Invoice")

    default_name = "Default"

    for invoice in Invoice.objects.filter(company__isnull=True).iterator():
        company, _created = Company.objects.get_or_create(
            organization_id=invoice.organization_id,
            owner_id=invoice.created_by_id,
            name=default_name,
            defaults={
                "tagline": "",
                "website": "",
                "phone": "",
                "email": "",
                "account_holder": "",
                "iban": "",
                "bic": "",
                "bank_name": "",
            },
        )
        Invoice.objects.filter(id=invoice.id).update(company_id=company.id)


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0003_invoice_pdf_template"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("tagline", models.CharField(blank=True, default="", max_length=255)),
                ("website", models.CharField(blank=True, default="", max_length=255)),
                ("phone", models.CharField(blank=True, default="", max_length=64)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("account_holder", models.CharField(blank=True, default="", max_length=255)),
                ("iban", models.CharField(blank=True, default="", max_length=64)),
                ("bic", models.CharField(blank=True, default="", max_length=32)),
                ("bank_name", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to="tenants.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("organization", "owner", "name")},
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="invoices.company",
            ),
        ),
        migrations.RunPython(backfill_invoice_company, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="invoice",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="invoices.company",
            ),
        ),
    ]
