# Generated by Django 5.1.5 on 2026-01-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0004_company_and_invoice_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("organization", "company", "invoice_number"),
                name="uniq_invoice_number_per_company",
            ),
        ),
    ]
